# Generated by Django 3.2.6 on 2021-08-27 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Médico')),
                ('cpf', models.CharField(max_length=20, verbose_name='CPF do Médico')),
                ('email', models.CharField(max_length=100, verbose_name='Email do Médico')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone do Médico')),
                ('crm', models.CharField(max_length=10, verbose_name='CRM do Médico')),
                ('especialidade', models.CharField(max_length=100, verbose_name='Especialidade do Médico')),
            ],
        ),
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Pacinte')),
                ('cpf', models.CharField(max_length=20, verbose_name='CPF do Pacinte')),
                ('email', models.CharField(max_length=100, verbose_name='Email do Pacinte')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone do Pacinte')),
                ('endereco', models.CharField(max_length=100, verbose_name='Endereço do Pacinte')),
                ('idade', models.CharField(max_length=3, verbose_name='Idade do Pacinte')),
            ],
        ),
    ]
