# Generated by Django 3.2.6 on 2021-08-27 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinicaMedica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientes',
            name='cpf',
            field=models.CharField(max_length=20, verbose_name='CPF do Paciente'),
        ),
        migrations.AlterField(
            model_name='pacientes',
            name='email',
            field=models.CharField(max_length=100, verbose_name='Email do Paciente'),
        ),
        migrations.AlterField(
            model_name='pacientes',
            name='endereco',
            field=models.CharField(max_length=100, verbose_name='Endereço do Paciente'),
        ),
        migrations.AlterField(
            model_name='pacientes',
            name='idade',
            field=models.CharField(max_length=3, verbose_name='Idade do Paciente'),
        ),
        migrations.AlterField(
            model_name='pacientes',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome do Paciente'),
        ),
        migrations.AlterField(
            model_name='pacientes',
            name='telefone',
            field=models.CharField(max_length=20, verbose_name='Telefone do Paciente'),
        ),
        migrations.CreateModel(
            name='Consultas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(verbose_name='Data da Consulta')),
                ('convenio', models.CharField(max_length=20, verbose_name='Convênio')),
                ('valor', models.CharField(max_length=10, verbose_name='Valor da Consulta')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinicaMedica.medicos')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinicaMedica.pacientes')),
            ],
        ),
    ]
